<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">  
<head>
<title> Albany Rowing Center <?= $title ? "-" : ""?> <?= $title ?> </title>

<link rel="stylesheet" type="text/css" href="style.css" />
</head>
<body>

<div id="header">
<img src="logo_cropped.jpg" alt="Albany Rowing Center, Albany New York" />
</div>

<div id="navcontainer">
<ul>
<li> <a href="/">Home</a> </li>
<li> <a href="about.php">About</a> </li>
<li> <a href="programs.php">Programs &amp; Camps</a>
<!--
<ul>
    <li> <a href="adult_programs.php">Adult Programs</a> </li>
    <li> <a href="junior_programs.php">Junior Programs</a> </li>
    <li> <a href="learn_to_row.php">Learn to Row</a> </li>
</ul> -->
</li>
<li> <a href="dates.php">Schedule &amp; Results</a> </li>
<li> <a href="docs.php">Forms &amp; Documents</a> </li>
<li> <a href="contact.php">Contact Us</a> </li>
</ul>
</div>
